import { requireOwner } from "@/lib/owner-access"
import { operations } from "@/lib/cockpit/operations"
import { Panel, Empty, Table, PrivateLink, Tag, shown } from "@/components/cockpit-ui"
import { HistoryView } from "./history-view"
const views = ["history","runs","routes","providers","cost","validation","failures"]
export default async function Telemetry({ searchParams }: { searchParams: Promise<{ view?: string; days?: string }> }) {
  await requireOwner()
  const params = await searchParams
  const days = ["1","7","30"].includes(params.days??"") ? Number(params.days) : 7
  const { data, state } = await operations()
  const view = views.includes(params.view??"") ? params.view! : data ? "runs" : "history"
  const now = Date.now(), start = days === 1 ? Date.parse(new Date().toISOString().slice(0,10)+"T00:00:00Z") : now - days * 86400000
  const runs = data?.runs.filter(r=>Date.parse(r.timestamp)>=start && Date.parse(r.timestamp)<=now) ?? []
  const groups = new Map<string, typeof runs>()
  for (const run of runs) { const key = `${run.provider??"Unavailable"} / ${run.model??"Unavailable"}`; groups.set(key,[...(groups.get(key)??[]),run]) }
  return <><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold">Detailed telemetry</h1><p className="mt-2 text-sm text-slate-500">Execution → route → evidence → validation → custody</p></div><Tag>{view==="history"?"Historical evidence":state}</Tag></div>
  <nav className="mb-6 flex flex-wrap gap-4">{views.map(v=><PrivateLink key={v} href={"/cockpit/telemetry?view="+v+"&days="+days}>{v==="routes"?"Route Ledger":v[0].toUpperCase()+v.slice(1)}</PrivateLink>)}</nav>
  {view==="history" ? <HistoryView/> : <>
  <div className="mb-6 flex flex-wrap gap-4 text-sm">{[1,7,30].map(d=><PrivateLink key={d} href={"/cockpit/telemetry?view="+view+"&days="+d}>{d===1?"Today (UTC)":`Last ${d} days`}</PrivateLink>)}</div>
  {!data && <div className="mb-6"><Empty>No validated operational source is connected. Historical candidate evidence is retained separately and is not counted as executions, calls, spend, or validation performance.</Empty></div>}
  {data && <p className="mb-6 text-sm text-slate-500">Source: {data.source} · Updated {data.generatedAt} · Coverage: {data.coverage}. {runs.length} recorded runs in selected period; completeness beyond this source is not assumed.</p>}
  <Panel title={{runs:"Run timeline",routes:"Route Ledger",providers:"Provider / model usage",cost:"Recorded cost",validation:"Validation checks",failures:"Failure & recovery"}[view]!}>
  {view==="runs" && <Table headings={["Run / time","Workstream","Capability / role","Provider / model","Duration","Outcome","Validation","Cost"]} rows={runs.map(r=>[<PrivateLink key={r.id} href={"/cockpit/telemetry/runs/"+r.id}>{r.id}<br/>{r.timestamp}</PrivateLink>,r.workstream,r.capability+" / "+shown(r.role),shown(r.provider)+" / "+shown(r.model),r.durationMs===null?"Unavailable":r.durationMs+" ms",r.outcome,r.validation,r.costUsd===null?"Unavailable":`$${r.costUsd.toFixed(4)} (${r.costBasis})`])}/>}
  {view==="routes" && <Table headings={["Run","Requested capability / role","Candidate","Selected","Rationale","Fallback / escalation","Result"]} rows={runs.map(r=>[<PrivateLink key={r.id} href={"/cockpit/telemetry/runs/"+r.id}>{r.id}</PrivateLink>,r.capability+" / "+shown(r.role),r.route.candidate,r.route.selected,r.route.rationaleCategory,shown(r.fallback)+" / "+shown(r.escalation),r.outcome])}/>}
  {view==="providers" && <Table headings={["Provider / model","Recorded runs","Tokens / missing","Mean duration / measured runs","Failed / recorded","Passed validation / recorded","Fallback / known"]} rows={[...groups].map(([key,rows])=>{const durations=rows.filter(r=>r.durationMs!==null),known=rows.filter(r=>r.fallback!==null);return [key,rows.length,rows.some(r=>r.tokens!==null)?`${rows.reduce((n,r)=>n+(r.tokens??0),0)} known / ${rows.filter(r=>r.tokens===null).length} missing`:"Unavailable",durations.length?`${Math.round(durations.reduce((n,r)=>n+r.durationMs!,0)/durations.length)} ms / ${durations.length}`:"Unavailable",`${rows.filter(r=>r.outcome==="failed").length} / ${rows.length}`,`${rows.filter(r=>r.validation==="passed").length} / ${rows.length}`,`${known.filter(r=>r.fallback).length} / ${known.length}`]})}/>}
  {view==="cost" && <><p className="mb-4">USD · Recorded amounts only. Actual and estimated values are never combined. A sum of known costs is not a complete bill.</p><Table headings={["Provider / model","Actual USD / measured","Estimated USD / measured","Missing cost"]} rows={[...groups].map(([key,rows])=>[key,...["actual","estimated"].map(basis=>{const included=rows.filter(r=>r.costBasis===basis&&r.costUsd!==null);return included.length?`$${included.reduce((n,r)=>n+r.costUsd!,0).toFixed(4)} / ${included.length}`:"Unavailable"}),rows.filter(r=>r.costUsd===null).length])}/><h3 className="my-4 font-semibold">By workstream</h3><Table headings={["Workstream","Actual USD","Estimated USD","Missing cost"]} rows={[...new Set(runs.map(r=>r.workstream))].map(w=>{const rows=runs.filter(r=>r.workstream===w);return [w,...["actual","estimated"].map(b=>{const values=rows.filter(r=>r.costBasis===b&&r.costUsd!==null);return values.length?values.reduce((n,r)=>n+r.costUsd!,0).toFixed(4):"Unavailable"}),rows.filter(r=>r.costUsd===null).length]})}/></>}
  {view==="validation" && <Table headings={["Run","Test","Expected","Observed","Status","Verifier","Failure / remediation"]} rows={runs.flatMap(r=>r.checks.map(c=>[<PrivateLink key={r.id+c.test} href={"/cockpit/telemetry/runs/"+r.id}>{r.id}</PrivateLink>,c.test,c.expected,c.observed,c.status,c.verifier,shown(c.failureCode)+" / "+shown(c.remediation)]))}/>}
  {view==="failures" && <Table headings={["Run","Failure class","Original route","Recovery","Result","Lesson","Rule changed"]} rows={runs.filter(r=>r.recovery).map(r=>[<PrivateLink key={r.id} href={"/cockpit/telemetry/runs/"+r.id}>{r.id}</PrivateLink>,r.recovery!.failureClass,r.route.selected,r.recovery!.action,r.recovery!.result,r.recovery!.lesson,shown(r.recovery!.durableRuleChanged)])}/>}
  </Panel><div className="mt-6 grid gap-4 md:grid-cols-2"><Panel title="Meaning & measurement"><p>Events describe a bounded execution or decision. Metrics use only timestamped records in the selected source and range. Missing measurements are not estimates; a recorded run is not automatically a provider API call.</p></Panel><Panel title="Trust boundary & custody"><p>Producer assertions and verifier results are distinct. The input must be sanitized by its trusted owner before ingestion; structural validation is not a general secret detector. Hash-verified artifacts are stored separately. Raw prompts, credentials and arbitrary documents are prohibited by this input contract.</p><p className="mt-3"><PrivateLink href="/cockpit/telemetry?view=history">Historical records and spend →</PrivateLink></p></Panel></div></>}</>
}
