import { notFound } from "next/navigation"
import { requireOwner } from "@/lib/owner-access"
import { operations } from "@/lib/cockpit/operations"
import { privateIndex } from "@/lib/cockpit/store"
import { Panel, Empty, Table, PrivateLink } from "@/components/cockpit-ui"
const sections: Record<string,string> = { workstreams: "Workstreams", evidence: "Evidence receipts", methodology: "Methodology", experiments: "Experiments", deployments: "Deployments", security: "Security / Audit" }
export default async function Section({ params }: { params: Promise<{ section: string }> }) {
  await requireOwner()
  const { section } = await params
  if (!sections[section]) notFound()
  const { data, state } = await operations()
  const index = (section === "evidence" || section === "methodology") ? await privateIndex() : null
  return <><h1 className="mb-6 text-3xl font-semibold">{sections[section]}</h1><p className="mb-5 text-sm text-slate-500">Operational source: {state} · Updated: {data?.generatedAt ?? "Unavailable"} · Coverage: {data?.coverage ?? "Unavailable"}</p>
  {section === "workstreams" && <Panel title="Current source"><Table headings={["Workstream","Status / gate","Owner","Next action","Blocker","Evidence"]} rows={(data?.workstreams ?? []).map(w=>[w.title,w.status+" / "+(w.gate??"Unavailable"),w.owner,w.nextAction,w.blocker,w.evidenceState])}/></Panel>}
  {section === "deployments" && <Panel title="Recorded deployments"><Table headings={["Deployment","Timestamp","Environment","Status","Evidence"]} rows={(data?.deployments ?? []).map(d=>[d.id,d.timestamp,d.environment,d.status,d.evidenceId])}/></Panel>}
  {section === "experiments" && <Panel title="Experiment custody"><Empty>No current experiment registry is connected. Preserved experiment records are historical and do not imply an active or approved next step.</Empty><p className="mt-4"><PrivateLink href="/cockpit/methodology">Browse preserved methodology →</PrivateLink></p></Panel>}
  {section === "security" && <div className="grid gap-5 xl:grid-cols-2"><Panel title="Access boundary"><p>Google OIDC identity is verified by Auth.js and bound to the configured immutable subject on the server. Every private handler and data loader rechecks authorization. Sessions have an eight-hour absolute deadline; logout clears the current browser session cookie. A copied JWT remains valid until its absolute deadline; changing the owner binding or rotating the session secret revokes authorization more broadly.</p><p className="mt-4">No email allowlist grants owner access. No client token storage or broader Google scopes are required.</p></Panel><Panel title="Audit custody & remaining gaps"><p>Login, logout, denied authorization and exports emit structured events to the server log sink. Retention and tamper-resistant storage depend on the hosting log configuration and have not been verified here.</p><p className="mt-4">No editing/deletion/configuration UI is enabled. Configuration and source changes remain in the deployment/Git custody process. Historical public repository copies and cached deployments require separate owner review.</p></Panel></div>}
  {(section === "evidence" || section === "methodology") && <div className="space-y-5"><Panel title={section === "methodology" ? "Preserved implementation library" : "Material claims"}>{section === "evidence" ? <Table headings={["Claim","Producer / verifier","Validation","Provenance","Limitations"]} rows={(data?.receipts??[]).map(e=>[e.claim,e.producer+" / "+(e.verifier??"Unavailable"),e.validationState,e.provenance,e.limitations])}/> : <p>Original architecture, role contracts, routing, validation and governance source is preserved as read-only evidence. The archive records a historical source version; it does not establish that every rule is current.</p>}</Panel><Panel title="Private archive · content verified on read">{!index ? <Empty>Private store unavailable. No archive metadata is inferred.</Empty> : <><p className="mb-4">Source version: {index.sourceCommit}. Custody: owner-managed private store; checksum verification before read or export.</p><Table headings={["Source / artifact","Type","Read"]} rows={index.entries.filter(e=>section==="methodology" ? e.kind==="source" : e.kind==="artifact").map(e=>[e.title,e.kind,<PrivateLink key={e.id} href={"/cockpit/evidence/"+e.id}>Inspect →</PrivateLink>])}/></>}</Panel></div>}
  </>
}
