import { requireOwner } from "@/lib/owner-access"
import { operations } from "@/lib/cockpit/operations"
import { Panel, Empty, PrivateLink, Tag } from "@/components/cockpit-ui"
import { library } from "@/lib/cockpit/library"
export default async function Overview() {
  await requireOwner()
  const { data, state } = await operations()
  const saved=await library()
  const today = new Date().toISOString().slice(0,10), runs = data?.runs.filter(r=>r.timestamp.startsWith(today)) ?? []
  const decisions = data?.workstreams.filter(w=>w.ownerDecision) ?? []
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Decision brief</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Your operating picture</h1><p className="mt-3 text-sm text-slate-500">What is running, what changed, and where to look next.</p></div><Tag>Telemetry · {state}</Tag></div>
  {!data && <div className="mb-6"><Empty>Operational telemetry is not connected. Values below remain unavailable until a validated, sanitized source is supplied. Preserved historical evidence is available separately.</Empty></div>}
  <div className="mb-6"><Panel title="Continue from your saved work"><p>{saved.total} saved source files and receipts · {data?.runs.length??0} recorded runs · {data?.deployments.length??0} deployment receipts</p><p className="mt-3">{data?.coverage??"Browse preserved reports while the operations source is unavailable."} Saved source statuses are historical.</p><div className="mt-4 flex flex-wrap gap-5"><PrivateLink href="/cockpit/learning/nbo-nrt">NBO / NRT learning journal →</PrivateLink><PrivateLink href="/cockpit/experiments">Experiment results →</PrivateLink><PrivateLink href="/cockpit/deployments">Deployment detail →</PrivateLink><PrivateLink href="/cockpit/evidence">Search all saved evidence →</PrivateLink><PrivateLink href="/cockpit/telemetry?view=history">Historical telemetry →</PrivateLink></div></Panel></div>
  <div className="grid gap-5 xl:grid-cols-3"><Panel title="Recorded deployment and checks"><dl className="space-y-3"><div>Latest saved deployment status: {data?.deployments.toSorted((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp))[0]?.status ?? "Unavailable"}</div><div>Source captured: {data?.generatedAt ?? "Unavailable"}</div><div>Failed recorded checks: {data ? data.runs.reduce((n,r)=>n+r.checks.filter(c=>c.status==="failed").length,0) : "Unavailable"}</div></dl><p className="mt-4"><PrivateLink href="/cockpit/deployments">Inspect deployments →</PrivateLink></p></Panel>
  <Panel title="AI operations"><p className="text-3xl font-semibold text-slate-900">{data ? runs.length : "—"}</p><p>Recorded runs today · UTC</p><p className="mt-3">Coverage: {data?.coverage ?? "Not established"}</p><p className="mt-4"><PrivateLink href="/cockpit/telemetry">Open run timeline →</PrivateLink></p></Panel>
  <Panel title="Cost"><p>Actual and estimated amounts are kept separate. Missing cost stays unknown.</p><p className="mt-4"><PrivateLink href="/cockpit/telemetry?view=cost">Today / 7 days / 30 days →</PrivateLink></p></Panel>
  <Panel title="Recorded workstreams">{data?.workstreams.length ? data.workstreams.map(w=><p key={w.id} className="mb-3"><strong>{w.title}</strong><br/>{w.status} · next: {w.nextAction ?? "Unavailable"}</p>) : <Empty>No current workstream feed is connected.</Empty>}<p className="mt-4"><PrivateLink href="/cockpit/workstreams">Inspect gates and blockers →</PrivateLink></p></Panel>
  <Panel title="Owner decisions required">{decisions.length ? decisions.map(w=><p key={w.id}>{w.title}: {w.ownerDecision}</p>) : <Empty>{data ? "No owner decisions are recorded in this source." : "Decision state unavailable; no decisions inferred from missing telemetry."}</Empty>}</Panel>
  <Panel title="Evidence & drift"><p>Preserved source and receipts retain provenance and content hashes. A migration snapshot does not establish current operational state or drift.</p><p className="mt-4"><PrivateLink href="/cockpit/evidence">Inspect evidence custody →</PrivateLink></p></Panel></div>
  <p className="mt-6 text-xs leading-6 text-slate-500">Meaning: recorded operations support owner decisions. Measurement: bounded to supplied source. Trust boundary: server-authorized owner access. Custody: private evidence store and source manifest.</p></>
}
